v5.0.0-next.14 (#680)
* deps: install missing deps to @roots/bud

* chore(deps): bump mini-css-extract-plugin to 2.4.2

* chore(deps-dev): Bump @roots/bud to v5.0.0-next.3

* deps: move server deps into @roots/bud-server

* deps: remove server deps from @roots/bud-support

* dev: remove logging from ncc

* yarn.lock

* chore(deps): pin dependencies (#579)

Co-authored-by: Renovate Bot <bot@renovateapp.com>

* chore(deps): bump jest monorepo to v27.3.1 (#578)

Co-authored-by: Renovate Bot <bot@renovateapp.com>

* chore(deps-dev): Bump @roots/bud to v5.0.0-next.4

* chore(deps): move some bud-server dev-deps to deps

* chore(deps-dev): Bump @roots/bud to v5.0.0-next.5

* dev: publish/version script

* dev: update deprecated prettier rule

* dev: modify dockerfile to auth verdaccio

* improve: server.proxy --> server.proxy.target

* dev: update deprecated prettier rule

* examples: add bedrock example

* dev: update dev/build/.yarnrc.yml

* site: update docs

* bedrock: update package.json and yarn.lock

* bud-react: remove problematic conditional check

* bedrock: update bud.config.js

* fix various interrelated settings

* update: server and middleware server-side scripts

* fix: client script

* fix(build): docker-compose.yml fixes

* chore(server): remove console.log()

* test: update snapshots

* fix(build): yarnrc use verdaccio server

* fix(build): use /bud as working directory

* chore: clean up yarn complaints

* examples: bedrock

* test: update jest build setup

* cli: fix a few flags

* dev: move css minimizer to api

* dev: also fix certain splitChunks config issues

* improve: alias

* improve: assets

* improve: assets

* improve: bud.dev

* improve: bud.minimize

* update: examples

the 5.0.0 release does not apply minification and splitChunks by
default.

Config files were updated so that integration tests would continue to
pass.

* factory typing

factory export takes a configuration object but it does not need to be
included in its entirety as it merged with the default config.

This change fixes the typing to reflect this.

* Improve: default splitChunks value is false

* improve: bud.publicPath

* improve: bud.use

* improve: integration start script

* tests: fix

* deps: add to root

add deps explicitly used by repo dev scripts to devDependencies

 Please enter the commit message for your changes. Lines starting

* specify runtimeChuk as undefined by default

* set parallelism option to cpu count - 1

* @roots/bud-api: move Repository to src root

* @roots/bud-api: move Repository definition to Repository dir

* @roots/bud-api: adjust src index for new pathing

* @roots/bud-compiler: fix issue with certain multi-compiler configs

* @roots/bud-babel: organize filesystem

* @roots/bud-babel: organize filesystem

* examples/bedrock: remove @tailwindcss/typography

* chore: update lockfile

* fix: @roots/bud-babel extension name

* fix(deps-dev): Remove nodejieba

* build(bud): use node image

* chore: update lockfile 🙈

* improve: various

* deps: upgrade/fix

* fix: deps and tests

* chore: i forgot to run `yarn install` again

* build(bud): gitignore .npmrc

* chore(test-imagemin): update snapshots

* chore(test-markdown): update snapshot

* chore(deps): pin dependencies (#581)

Co-authored-by: Renovate Bot <bot@renovateapp.com>

* chore(deps-dev): Pin dependencies

* type wdm wrapper fn compiler prop with any

* dev: add uglify-js and webpack to ncc excludes

* tsdoc: remove @extension tag

* tsdoc: remove @extension tag

* chore(deps): bump @types/eslint to v7.28.2 (#582)

Co-authored-by: Renovate Bot <bot@renovateapp.com>

* chore(deps): bump sass to v1.43.3 (#586)

Co-authored-by: Renovate Bot <bot@renovateapp.com>

* chore(deps): bump @types/react to v17.0.31 (#583)

Co-authored-by: Renovate Bot <bot@renovateapp.com>

* fix(deps): bump html-loader to v3 (#589)

Co-authored-by: Renovate Bot <bot@renovateapp.com>

* chore(deps): bump @types/lodash to v4.14.176 (#580)

Co-authored-by: Renovate Bot <bot@renovateapp.com>

* chore(deps-dev): Bump @roots/bud to v5.0.0-next.6

* improve: various improvements

* chore(deps-dev): Bump @roots/bud to v5.0.0-next.7

* improve: minor improvements

* improve: update examples

* improve: cli

* improve: cli runner

* improve: bud.dependencies (installer)

* improve: bud.project.peers (module discovery)

* improve: add manifestPath to bud.project store

* improve: clean feature flag enabled by default

* improve: bud.dev --> bud.serve; improve: bud.proxy

* fix: do not validate cache based on cache

* tests: update bud.dev --> bud.serve

* chore(deps): bump @yarnpkg/builder to v3.1.0-rc.10 (#593)

Co-authored-by: Renovate Bot <bot@renovateapp.com>

* chore(deps): bump esbuild to v0.13.9 (#594)

Co-authored-by: Renovate Bot <bot@renovateapp.com>

* chore(deps): bump @types/react to v17.0.32

* chore(deps): bump @types/tailwindcss to v2.2.2

* improve: caching

* tests: update tests/examples

* tests: update setup scripts

* conditional bud.project rebuilds based on cache

* added: dump and dd methods

* build: use location hooks for resolve.modules

* framework: reorder imports (lint result)

* tests: fix unit tests

* fix: bud init

* improve: clean root exports in extensions

* improve: @roots/bud-imagemin

* improve: @roots/bud-sass

* improve: @roots/bud-solid

* improve: @roots/bud-tailwindcss

* improve: @roots/bud-vue

* sass: fix

* lockfile

* change resolver workspace path

* add teardown script

* tests: update jest suites

* tests: update jest setup/teardown

* fix: eslint & sage snapshot

* fix: gh runner modules resolution

* async bootstrap (#603)

Co-authored-by: QWp6t <hi@qwp6t.me>

* chore(deps): bump @microsoft/api-documenter to v7.13.67

* chore(deps): pin dependencies

* chore(deps): bump @microsoft/api-extractor to v7.18.19

* chore(deps): bump @types/react to v17.0.34

* chore(deps): bump @types/react-dom to v17.0.11

* chore(deps): bump webpack to v5.62.1 (#588)

Co-authored-by: Renovate Bot <bot@renovateapp.com>
Co-authored-by: QWp6t <QWp6t@users.noreply.github.com>

* fix(deps): bump @yarnpkg/cli to v3.1.0 (#612)

Co-authored-by: Renovate Bot <bot@renovateapp.com>

* fix(deps): bump @yarnpkg/shell to v3.1.0 (#614)

Co-authored-by: Renovate Bot <bot@renovateapp.com>

* chore(deps): bump @types/react-router-dom to v5.3.2 (#601)

Co-authored-by: Renovate Bot <bot@renovateapp.com>

* chore(deps): bump typedoc to v0.22.8 (#610)

Co-authored-by: Renovate Bot <bot@renovateapp.com>

* chore(deps): bump html-webpack-plugin to v5.5.0 (#618)

Co-authored-by: Renovate Bot <bot@renovateapp.com>

* chore(deps): bump babel monorepo to v7.16.0 (#616)

Co-authored-by: Renovate Bot <bot@renovateapp.com>

* chore(deps): bump solid-js to v1.2.2 (#619)

Co-authored-by: Renovate Bot <bot@renovateapp.com>

* chore(deps): bump css-loader to v6.5.1 (#617)

Co-authored-by: Renovate Bot <bot@renovateapp.com>

* fix(deps): bump postcss-scss to v4.0.2 (#615)

Co-authored-by: Renovate Bot <bot@renovateapp.com>

* chore(deps): bump typescript-eslint monorepo to v5.3.0 (#620)

Co-authored-by: Renovate Bot <bot@renovateapp.com>

* fix(deps): bump sass-loader to v12.3.0 (#621)

Co-authored-by: Renovate Bot <bot@renovateapp.com>

* chore(deps): bump node.js to v16.13.0 (#622)

Co-authored-by: Renovate Bot <bot@renovateapp.com>
Co-authored-by: QWp6t <QWp6t@users.noreply.github.com>

* chore(deps): bump css-minimizer-webpack-plugin to v3.1.2 (#625)

Co-authored-by: Renovate Bot <bot@renovateapp.com>

* chore(deps): bump type-fest to v2.5.2 (#609)

Co-authored-by: Renovate Bot <bot@renovateapp.com>

* chore(deps): bump sass to v1.43.4 (#605)

Co-authored-by: Renovate Bot <bot@renovateapp.com>

* chore(deps): bump esbuild to v0.13.12 (#604)

Co-authored-by: Renovate Bot <bot@renovateapp.com>

* chore(deps): bump docusaurus monorepo to v2.0.0-beta.9 (#607)

Co-authored-by: Renovate Bot <bot@renovateapp.com>

* chore(deps): bump yarnpkg monorepo to v3.1.0 (#624)

Co-authored-by: Renovate Bot <bot@renovateapp.com>

* chore(deps): bump tailwindcss to v2.2.19 (#608)

Co-authored-by: Renovate Bot <bot@renovateapp.com>

* chore(deps): bump vue monorepo to v3.2.21 (#611)

Co-authored-by: Renovate Bot <bot@renovateapp.com>

* chore(deps-dev): Bump @roots/bud to v5.0.0-next.8

* fix: @roots/bud-support packaging

* fix: dashboard dependencies

* fix: race condition with server settings

* fix(test-babel): i have no idea what i'm doing but it worked

* test runner: remove all project

* fix: bud.use extension race condition

* fix: race condition with examples/babel integration test

* chore(deps): bump @microsoft/api-documenter to v7.13.68

* chore(deps): bump @types/node to v16.11.7 (#627)

Co-authored-by: Renovate Bot <bot@renovateapp.com>

* fix: hmr scripts

* chore(deps): pin dependencies

* chore(deps): bump esbuild to v0.13.13

* improve: json5/ts/yml parsing

* fix: tests. add: proxy/dev logging

* fix: tests

* fix(tests): update to match new config

* chore(deps): pin @types/js-yaml to 4.0.4 (#630)

Co-authored-by: Renovate Bot <bot@renovateapp.com>

* chore(deps): bump react monorepo (#638)

Co-authored-by: Renovate Bot <bot@renovateapp.com>

* chore(deps): bump webpack to v5.63.0 (#639)

Co-authored-by: Renovate Bot <bot@renovateapp.com>

* chore(deps): bump css-minimizer-webpack-plugin to v3.1.3

* improved logging and caching

* chore(deps): bump typescript-eslint monorepo to v5.3.1 (#635)

Co-authored-by: Renovate Bot <bot@renovateapp.com>

* chore(deps): bump eslint-plugin-import to v2.25.3 (#632)

Co-authored-by: Renovate Bot <bot@renovateapp.com>

* chore(deps): bump eslint-plugin-react to v7.27.0 (#637)

Co-authored-by: Renovate Bot <bot@renovateapp.com>

* chore(deps): bump solid-js to v1.2.3 (#633)

Co-authored-by: Renovate Bot <bot@renovateapp.com>

* fix(deps): bump @oclif/plugin-help to v3.2.4 (#636)

Co-authored-by: Renovate Bot <bot@renovateapp.com>

* chore(deps): bump type-fest to v2.5.3 (#634)

Co-authored-by: Renovate Bot <bot@renovateapp.com>

* improved logging and cli flags

* fix: error TS6133

* fix(test-cli): update snapshot

* chore(deps): pin ink-spinner to 4.0.3 (#640)

Co-authored-by: Renovate Bot <bot@renovateapp.com>

* chore(deps): bump @easyops-cn/docusaurus-search-local to v0.20.0 (#641)

Co-authored-by: Renovate Bot <bot@renovateapp.com>

* chore(deps): bump copy-webpack-plugin to v9.1.0 (#642)

Co-authored-by: Renovate Bot <bot@renovateapp.com>

* chore(deps): bump webpack to v5.64.0 (#643)

Co-authored-by: Renovate Bot <bot@renovateapp.com>

* chore(deps-dev): Bump @roots/bud to v5.0.0-next.9

* fix: tests

* improve: bud doctor

* improve: logging

* fix: dont attempt to call configs on no config builds

* chore(deps): bump @types/prettier to v2.4.2 (#644)

Co-authored-by: Renovate Bot <bot@renovateapp.com>

* fix: slew of tests

* fix: doctor

* fix: proxy

* fix(test-babel): update snapshot

* fix(test-server): update snapshot

* fix(server-config): remove leading space

* chore(deps-dev): Bump @roots/bud to v5.0.0-next.10

* fix(proxy-interceptor): use `.replaceAll()`

* chore(deps-dev): Bump @roots/bud to v5.0.0-next.11

* fix: middleware.hot.publish

* chore(deps): pin http-proxy-middleware to 2.0.1

* chore(deps): bump emotion monorepo to v11.6.0

* chore(deps-dev): Bump @roots/bud to v5.0.0-next.12

* fix: installer

* fix: doctor

* fix: failing tests

* chore(deps): bump typedoc to v0.22.9

* chore(deps): bump vue monorepo to v3.2.22

* fix(deps): bump stylelint-config-standard to v24 (#652)

Co-authored-by: Renovate Bot <bot@renovateapp.com>

* chore(deps): bump typescript-eslint monorepo to v5.4.0 (#651)

Co-authored-by: Renovate Bot <bot@renovateapp.com>

* chore(deps): bump @types/eslint to v7.29.0 (#650)

Co-authored-by: Renovate Bot <bot@renovateapp.com>

* chore(deps): bump @types/react to v17.0.35 (#654)

Co-authored-by: Renovate Bot <bot@renovateapp.com>

* chore(deps): bump webpack to v5.64.1 (#649)

Co-authored-by: Renovate Bot <bot@renovateapp.com>

* chore(deps): bump @types/lodash to v4.14.177 (#653)

Co-authored-by: Renovate Bot <bot@renovateapp.com>

* ci(workflows-labeler):update labels

* chore(deps): bump esbuild to v0.13.14 (#655)

Co-authored-by: Renovate Bot <bot@renovateapp.com>

* improved async handling

* fix: failing tests & hooks event keys

* sage: remove setPath calls

* fix: entry

* tests: update snapshot and fix

* fix: wordpress theme example

* chore(deps): bump postcss-preset-env to v7 (#658)

Co-authored-by: Renovate Bot <bot@renovateapp.com>

* chore(deps): bump @vercel/ncc to v0.32.0 (#657)

Co-authored-by: Renovate Bot <bot@renovateapp.com>

* chore(deps): pin @types/safe-json-stringify to 1.1.2 (#656)

Co-authored-by: Renovate Bot <bot@renovateapp.com>

* fix: jankiness

* chore(deps-dev): Bump @roots/bud to v5.0.0-next.13

* fix: deps

* improve: tests

* fix: skip failing tsconfig test error

* fix: various minor issues

* chore(deps): bump css-minimizer-webpack-plugin to v3.1.4 (#659)

Co-authored-by: Renovate Bot <bot@renovateapp.com>

* chore(deps): bump solid-js to v1.2.4 (#660)

Co-authored-by: Renovate Bot <bot@renovateapp.com>

* chore(deps-dev): Bump @roots/bud to v5.0.0-next.14

Co-authored-by: Kelly Mears <developers@tinypixel.dev>
Co-authored-by: QWp6t <hi@qwp6t.me>
Co-authored-by: renovate[bot] <29139614+renovate[bot]@users.noreply.github.com>
Co-authored-by: Renovate Bot <bot@renovateapp.com>
Co-authored-by: QWp6t <QWp6t@users.noreply.github.com>